### ISSUE TITLE
Reading or writing in-memory would be great.

### ISSUE THREAD

**Issue by tjltjl** [lukas-shawford/gltflib#236]
I'm currently kludging around by reimplementing the load and save outside of GLTF to go directly in-memory. The best would be to be able to pass binary data or at least a io.BytesIO directly somewhere in the API.

I can make a pull request of this, just let me know how you'd like it to be implemented

**Comment by lukas-shawford** [comment]
This would be a great addition!

I'm thinking there should be 2 additional static class methods on the `GLTF` class for reading from a stream: `read_gltf` and `read_glb` (since we do not have a filename, we cannot infer from the extension whether it is a plain-text glTF or a binary GLB, so we need to be explicit - hence the 2 separate methods).

Then the `load_gltf` method can be refactored to use `read_gltf`, and `load_glb` can be refactored to use `read_glb`.

The `read_gltf` method should have more or less the same signature as `load_gltf`, except it takes a `stream: BinaryIO` instead of a `filename: str` parameter. It should also have an additional `basepath` (optional) parameter, since we cannot infer the basepath from filename.

For writing, I'm also thinking 2 additional methods, `write_gltf` and `write_glb`, with same signatures as their corresponding `export_` methods, but with a `stream: BinaryIO` instead of a `filename: str` parameter. Again, `export_gltf` and `export_glb` can be refactored to use the `write_` methods.

Does that sounds like a decent approach? It's been a while since I poked around with this project (or with Python in general), so let me know if anything sounds off!

**Comment by lukas-shawford** [comment]
I just merged both PRs and made a new release, 1.0.13, containing these changes. Thanks for the contribution!

If you get a chance to pull down the latest release and give it a try, let me know if you see any issues.
